default-group: "default"
resolution-policy: "PRIMARY_WINS"

storage:
  backend: "mysql"
  host: "localhost"
  port: 3306
  database: "nixperms"
  username: "root"
  password: ""
  pool-size: 10

sync:
  enabled: true
  poll-interval: 3000

user-cache-expire-seconds: 0
wildcard-resolution: true